export {About} from "./about"
export {HeroSection} from "./heroSection"
export {CoursesSection} from "./courseSection"
export {HeroSectionMobile} from "./heroSectionMobile"
export {InstrumentsSection} from "./instrumentsSection"
export {FaqSection} from "./faqSection"
export {CtaBanner} from "./ctaBanner"